#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/ios-proxy-app/whitelist-bypass-proxy/WtBusSecrets.swift"
load_env_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  while IFS='=' read -r k v; do
    [[ -n "$k" && "$k" != \#* ]] || continue
    v="${v%$'\r'}"; v="${v%\"}"; v="${v#\"}"; v="${v%\'}"; v="${v#\'}"
    case "$k" in
      WTBUS_KEY_B64|WTBUS_KEY_ID|VK_BOT_TOKEN|VK_BOT_PEER_ID) export "$k=$v" ;;
    esac
  done < "$f"
}
load_env_file "$ROOT/.env"
load_env_file "$ROOT/ios-proxy-app/.env"
load_env_file "$ROOT/android-app/.env"
esc() { python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "${1:-}"; }
cat > "$OUT" <<SWIFT
import Foundation

// Generated by scripts/generate-ios-secrets.sh. Do not commit real secrets.
enum WtBusSecrets {
    static let keyB64 = $(esc "${WTBUS_KEY_B64:-}")
    static let keyID = $(esc "${WTBUS_KEY_ID:-k1}")
    static let vkBotToken = $(esc "${VK_BOT_TOKEN:-}")
    static let vkBotPeerID = $(esc "${VK_BOT_PEER_ID:-46887791}")
}
SWIFT
if [[ -n "${WTBUS_KEY_B64:-}" ]]; then
  echo "Generated iOS WtBusSecrets.swift with WTBUS key and VK peer ${VK_BOT_PEER_ID:-46887791}"
else
  echo "Generated iOS WtBusSecrets.swift with empty secrets; private/encrypted discovery disabled" >&2
fi
