import Foundation

// Generated by scripts/generate-ios-secrets.sh. Do not commit real secrets.
enum WtBusSecrets {
    static let keyB64 = "ZeL_22FTRPa1ZjyUows6BSd-oLwjGqF3kjiYNXAu0ak"
    static let keyID = "k1"
    static let vkBotToken = "vk1.a.PEjJj7wn7iYChC5pdSNP4z4-QZN_R98JELQ4AI82MtiE9MmN2MiDyhMCh2rr6Os9d2MR4LK-w6iXjmxoCRJXxEXYzlOTUJ-5fwViS6y69dYxuczqbN_ukDFOffttvD1DYMYtxpUmJyTJixA9bC1knOWPUuFJAgKqk2IGDF7HAyl3wCsu8PcdIJfArD9SNdSoqeji85s2uOUhkXzHmV-jqQ"
    static let vkBotPeerID = "46887791"
}
